name: 'cached-checkout'
description: 'cache, then checkout'

inputs:
  repo:
    description: 'the name of repo to checkout, like <owner>/<name>, for example mdn/content'
    required: true
  path:
    required: true
  fetch-depth:  
    description: 'pass to action/checkout. number of commits to fetch. 0 indicates all history for all branches and tags.'
    required: false
    default: 1
    
# no outputs

runs:
  using: "composite"
  steps:
    - name: Get Latest Commit Hash
      bash: powershell
      run: |
        $commits = Invoke-WebRequest -Uri 'https://api.github.com/repos/${{inputs.repo}}/commits?per_page=1' -Method Get | ConvertFrom-Json
        $latestHash = $commits[0].sha
        Write-Host '$latestHash' $latestHash
        echo "latest-hash=$latestHash" >> $env:GITHUB_ENV
    
    - if: inputs.fetch-depth != 0
      name: Cache repo (not 0)
      uses: actions/cache@v4.2.0
      with:
        path: ${{ inputs.path }}
        key: translated-content depth${{ inputs.fetch-depth }} ${{ env.latest-hash }}
        restore-keys: |
          translated-content depth${{ inputs.fetch-depth }}
          translated-content

    - if: inputs.fetch-depth == 0
      name: Cache repo (0)
      uses: actions/cache@v4.2.0
      with:
        path: ${{ inputs.path }}
        key: translated-content depth${{ inputs.fetch-depth }} ${{ env.latest-hash }}
        restore-keys: |
          translated-content depth${{ inputs.fetch-depth }}
       
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        path: ${{ inputs.path }}
        fetch-depth: ${{ inputs.fetch-depth }}

