name: 'cached-checkout'
description: 'cache, then checkout'

inputs:
  repo:
    description: 'the name of repo to checkout, like <owner>/<name>, for example mdn/content'
    required: true
  path:
    required: true
  fetch-depth:  
    description: 'pass to action/checkout. number of commits to fetch. 0 indicates all history for all branches and tags.'
    required: false
    default: 1
    
outputs:
  latest-hash:
    value: ${{ steps.get-hash.outputs.latest-hash }}

runs:
  using: "composite"
  steps:
    - name: Get Latest Commit Hash
      id: get-hash
      shell: powershell
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $whyMustHere = @{
          'authorization' = 'Bearer $GITHUB_TOKEN'
        }
        $commits = Invoke-WebRequest -Uri 'https://api.github.com/repos/${{inputs.repo}}/commits?per_page=1' -Headers $whyMustHere -Method Get | ConvertFrom-Json
        $latestHash = $commits[0].sha
        Write-Host '$latestHash' $latestHash
        echo "latest-hash=$latestHash" >> $env:GITHUB_OUTPUT
    
    - name: Cache repo
      id: cache
      uses: actions/cache@v4.2.0
      with:
        path: ${{ inputs.path }}
        key: ${{inputs.repo}} depth${{ inputs.fetch-depth }} ${{ steps.get-hash.outputs.latest-hash }}
        restore-keys: |
          ${{inputs.repo}} depth${{ inputs.fetch-depth }}
          ${{inputs.repo}}
       
    - if: steps.cache.outputs.cache-hit != 'true'
      name: Checkout repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        path: ${{ inputs.path }}
        fetch-depth: ${{ inputs.fetch-depth }}

