name: check l10n.sourceCommit

on:
  # schedule:
  # - cron: ""
  workflow_dispatch:

jobs:
  check_sourceCommit:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'script'

      - name: Checkout mdn/translated-content
        uses: actions/checkout@v4
        with:
          repository: 'mdn/translated-content'
          path: 'translated-content'
            
      - name: Checkout mdn/content
        uses: actions/checkout@v4
        with:
          repository: 'mdn/content'
          path: 'content'
          fetch-depth: '0'

      - name: run script
        run: |
          $en_folder = (Resolve-Path -Path "content\files\en-us").Path
          $zh_folder = (Resolve-Path -Path "translated-content\files\zh-cn").Path
          $env:GIT_DIR = ".\content\.git"
          $env:GIT_WORK_TREE = ".\content"
          Write-Host $en_folder $zh_folder $env:GIT_DIR $env:GIT_WORK_TREE
          
          $files = Get-ChildItem -Path $zh_folder -Recurse -File -Filter "*.md"
          Write-Host $files.Length
          $files | Select-Object -First 6 | Write-Host
          
          $files = $files | Select-Object -ExpandProperty FullName
          Write-Host $files.Length
          $files | Select-Object -First 6 | Write-Host
          
          $commitDistances = [System.Collections.Generic.List[PSObject]]::new()
          $badFrontMatter = [System.Collections.Generic.List[String]]::new()
          
          ForEach ($file in $files) {
              $file_start = -join (Get-Content -Path $file -TotalCount 6)
              if ($file_start -match "\s{1,}sourceCommit:\s?([0-9a-f]{40})") {
                  $relative_path = $file -replace [regex]::Escape($translation_folder), ""
                  $en_file = Join-Path -Path $en_folder -ChildPath $relative_path
                  $the_redundant_variable_to_remove_the_whitespace = $Matches[1] + "..HEAD"
                  $commitDistances.add([PSCustomObject]@{
                      File = $file
                      Distance = git rev-list --count $the_redundant_variable_to_remove_the_whitespace -- $en_file
                  })
              } else {
                  $badFrontMatter.add($file)
              }
          }
          
          $commitDistances.ToArray() | Export-Csv -Path "distances.csv" -NoTypeInformation
          $badFrontMatter | Out-File -FilePath "no_sourceCommit.txt" -Encoding ascii

      - name: Create artifact distances.csv
        uses: actions/upload-artifact@v4.6.0
        with:
          name: distances.csv
          path: distances.csv

      - name: publish distances.csv to gist
        uses: ./.github/workflows/publish.yml
        with:
          filename: distances.csv

      - name: Create artifact no_sourceCommit.txt
        uses: actions/upload-artifact@v4.6.0
        with:
          name: no_sourceCommit.txt
          path: no_sourceCommit.txt

      - name: publish no_sourceCommit.txt to gist
        uses: ./.github/workflows/publish.yml
        with:
          filename: no_sourceCommit.txt
