name: check l10n.sourceCommit

on:
  # schedule:
  # - cron: ""
  workflow_dispatch:

env:
  file_distances_name: "distances.csv" # when it, also change jobs.publish_distances.with.filename
  file_no_sourceCommit_name: "no_sourceCommit.txt" #  when it, also change change jobs.publish_no_sourceCommit.filename

jobs:
  check_sourceCommit:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: cache and checkout mdn/translated-content
        uses: ./.github/actions/cached-checkout
        with:
          repo: mdn/translated-content
          path: translated-content

      - name: cache and checkout mdn/content (depth 0)
        uses: ./.github/actions/cached-checkout
        with:
          repo: mdn/content
          path: content
          fetch-depth: 0

      - name: Debug Info
        run: |
          ls

      - name: run script
        run: |
          $en_folder = (Resolve-Path -Path "content\files\en-us").Path
          $zh_folder = (Resolve-Path -Path "translated-content\files\zh-cn").Path
          $env:GIT_DIR = ".\content\.git"
          $env:GIT_WORK_TREE = ".\content"
          Write-Host $en_folder $zh_folder $env:GIT_DIR $env:GIT_WORK_TREE
          
          $files = Get-ChildItem -Path $zh_folder -Recurse -File -Filter "*.md"
          Write-Host $files.Length
          $files | Select-Object -First 6 | Write-Host
          
          $files = $files | Select-Object -ExpandProperty FullName
          Write-Host $files.Length
          $files | Select-Object -First 6 | Write-Host
          
          $commitDistances = [System.Collections.Generic.List[PSObject]]::new()
          $badFrontMatter = [System.Collections.Generic.List[String]]::new()
          
          ForEach ($file in $files) {
              $file_start = -join (Get-Content -Path $file -TotalCount 6)
              if ($file_start -match "\s{1,}sourceCommit:\s?([0-9a-f]{40})") {
                  $relative_path = $file -replace [regex]::Escape($translation_folder), ""
                  $en_file = Join-Path -Path $en_folder -ChildPath $relative_path
                  $the_redundant_variable_to_remove_the_whitespace = $Matches[1] + "..HEAD"
                  $commitDistances.add([PSCustomObject]@{
                      File = $file
                      Distance = git rev-list --count $the_redundant_variable_to_remove_the_whitespace -- $en_file
                  })
              } else {
                  $badFrontMatter.add($file)
              }
          }
          
          $commitDistances.ToArray() | Export-Csv -Path ${{ env.file_distances_name }} -NoTypeInformation
          $badFrontMatter | Out-File -FilePath ${{ env.file_no_sourceCommit_name }} -Encoding ascii

      - name: Create artifact ${{ env.file_distances_name }}
        uses: actions/upload-artifact@v4.6.0
        with:
          name: ${{ env.file_distances_name }}
          path: ${{ env.file_distances_name }}
          retention-days: 14

      - name: Create artifact no_sourceCommit.txt
        uses: actions/upload-artifact@v4.6.0
        with:
          name: ${{ env.file_no_sourceCommit_name }}
          path: ${{ env.file_no_sourceCommit_name }}
          retention-days: 14

  publish_distances:
    uses: ./.github/workflows/publish.yml
    needs: check_sourceCommit
    with:
      filename: "distances.csv"
    secrets:
      ACCOUNT_TOKEN_GIST: ${{ secrets.ACCOUNT_TOKEN_GIST }}

  publish_no_sourceCommit:
    uses: ./.github/workflows/publish.yml
    needs: check_sourceCommit
    with:
      filename: "no_sourceCommit.txt"
    secrets:
      ACCOUNT_TOKEN_GIST: ${{ secrets.ACCOUNT_TOKEN_GIST }}
