name: check l10n.sourceCommit

on:
  # schedule:
  # - cron: ""
  workflow_dispatch:

jobs:
  check_sourceCommit:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Checkout mdn/translated-content
        uses: actions/checkout@v4
        with:
          repository: 'mdn/translated-content'
          path: 'translated-content'
          
      - name: Checkout mdn/content
        uses: actions/checkout@v4
        with:
          repository: 'mdn/content'
          path: 'content'
          fetch-depth: '0'
          
      - name: set var and env
        run: |
          $en_folder = Resolve-Path -Path "content\files\en-us"
          $translation_folder = Resolve-Path -Path "translated-content\files"
          $env:GIT_DIR = ".\content\.git"
          $env:GIT_WORK_TREE = ".\content"
          Write-Host $en_folder $translation_folder $env:GIT_DIR $env:GIT_WORK_TREE

      - name: run script
        run: |
          $commitDistances = [System.Collections.Generic.List[PSObject]]::new()
          $badFrontMatter = [System.Collections.Generic.List[String]]::new()
          
          $files = Get-ChildItem -Path $translation_folder -Recurse -File -Filter "*.md"
          $files = Select-Object -InputObject $files -ExpandProperty FullName
          Write-Host $files.Length
          $files | Select-Object -First 6 | Write-Host
          ForEach-Object -InputObject $files {
              $file_start = -join (Get-Content -Path $_ -TotalCount 6)
              if($file_start -match "\s{1,}sourceCommit:\s?([0-9a-f]{40})"){
                  $relative_path = $_ -replace [regex]::Escape($translation_folder), ""
                  $en_file = Join-Path -Path $en_folder -ChildPath $relative_path
                  $the_redundant_variable_to_remove_the_whitespace = $Matches[1]+"..HEAD"
                  $commitDistances.add(
                      [PSCustomObject]@{
                          File = $_
                          Distance = git rev-list --count $the_redundant_variable_to_remove_the_whitespace -- $en_file
                          #FrontHash = $Matches[1]
                          #CurrentHash = git log --format=%H -1 -- $en_file
                      }
                  )
                  # Write-Host "$en_file"
                  # Write-Host $the_redundant_variable_to_remove_the_whitespace
              } else {
                  $badFrontMatter.add($_)
              }
          }
          $commitDistances.ToArray() | Export-Csv -Path "distances.csv" -NoTypeInformation
          $badFrontMatter | Out-File -FilePath "no_sourceCommit.txt" -Encoding ascii
          $env:commitDistances = GetContent -Path "distances.csv" -Raw -Encoding ascii
          $env:badFrontMatter = GetContent -Path "no_sourceCommit.txt" -Raw -Encoding ascii
          
      - name: publish distances.csv to gist
        uses: ./.github/workflows/publish.yml
        with:
          filename: distances.csv
          content: ${{ env.commitDistances }}

      - name: publish no_sourceCommit.txt to gist
        uses: ./.github/workflows/publish.yml
        with:
          filename: no_sourceCommit.txt
          content: ${{ env.badFrontMatter }}
