name: integrate 4 files

on:
  schedule:
    - cron: "42 22 * * 2,6"
  workflow_dispatch:

env:
  file_distances_name: "distances.csv"
  file_no_sourceCommit_name: "no_sourceCommit.txt"
  file_last_date_name: "last_commit_date.csv"
  file_untranslated_name: "untranslated.txt" # when change names, also change /integrate.py

jobs:
  main:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
          
      - run: pip install -r requirements.txt
      
      - name: cache and checkout mdn/translated-content (depth 0)
        uses: ./.github/actions/cached-checkout
        with:
          repo: mdn/translated-content
          path: translated-content
          fetch-depth: 0

      - name: cache and checkout mdn/content (depth 0)
        id: get-content
        uses: ./.github/actions/cached-checkout
        with:
          repo: mdn/content
          path: content
          fetch-depth: 0

      - name: check last commit date
        run: |
          $logFile = "md_logs.txt"
          $targetFiles = "current_files.txt"
          $env:GIT_DIR = ".\translated-content\.git"
          $env:GIT_WORK_TREE = ".\translated-content"
          
          git log --format=%ad --date=short --name-only | Out-File -FilePath $logFile -Encoding ascii
          git ls-files *.md | Out-File -FilePath $targetFiles -Encoding ascii
          python get_last_commit_dates.py $logFile ${{env.file_last_date_name}} $targetFiles
          rm $logFile
          rm $targetFiles

      - name: check untranslated
        run: |
          $languages = "es", "fr", "ja", "ko", "pt-br", "ru", "zh-cn", "zh-tw"
          $en_folder = (Resolve-Path -Path "content\files\en-us").Path
          $translation_mu = (Resolve-Path -Path "translated-content\files\$lang").Path

          $translation_si_list = $languages | ForEach-Object {
              $x = Join-Path -Path $translation_mu -ChildPath $_
              if (!(Test-Path -Path $x)) { throw "path error: language code. `n $languages `n $x `n" }
              $x
          }
          
          Get-ChildItem -Path $en_folder -Recurse -File -Filter "*.md" | `
          Select-Object -ExpandProperty FullName | `
          ForEach-Object {
              foreach( $translation_si in $translation_si_list ) {
                  $relative_path = [System.IO.Path]::GetRelativePath($en_folder, $_)
                  $translation_file = Join-Path -Path $translation_si -ChildPath $relative_path
                  
                  if (!(Test-Path -Path $translation_file)) {
                      [System.IO.Path]::GetRelativePath($translation_mu, $translation_file)
                  }
              }
          } | Out-File -FilePath "${{ env.file_untranslated_name }}" -Encoding ascii

      - name: check sourceCommit
        run: |
          $env:GIT_DIR = ".\content\.git"
          $env:GIT_WORK_TREE = ".\content"
          $languages = "es", "fr", "ja", "ko", "pt-br", "ru", "zh-cn", "zh-tw"
          
          $en_folder = (Resolve-Path -Path "content\files\en-us").Path
          $translation_mu = (Resolve-Path -Path "translated-content\files\").Path
          
          $languages | ForEach-Object {
              $x = Join-Path -Path $translation_mu -ChildPath $_
              if (!(Test-Path -Path  $x)) {
                  throw "path error: language code. Anncounced $languages, but $x is not found."
              }
          }
          
          $commitDistances = [System.Collections.Generic.List[PSObject]]::new()
          $badFrontMatter = [System.Collections.Generic.List[String]]::new()
          
          foreach ($lang in $languages) {
              write-host "Starting $lang"
              $translation_folder = (Resolve-Path -Path "translated-content\files\$lang").Path
              $files = Get-ChildItem -Path $translation_folder -Recurse -File -Filter "*.md"|`
                  Select-Object -ExpandProperty FullName
              write-host "Found $($files.Count) files in $lang"
              ForEach ($file in $files) {
                  $file_start = -join (Get-Content -Path $file -TotalCount 6)
                  $relative_path = [System.IO.Path]::GetRelativePath($translation_folder, $file)
                  if ($file_start -match "\s{1,}sourceCommit:\s?([0-9a-f]{40})") {
                      $en_file = Join-Path -Path $en_folder -ChildPath $relative_path
                      $commitDistances.add([PSCustomObject]@{
                          File = "$lang\$relative_path"
                          Distance = git rev-list --count "$($Matches[1])..HEAD" -- $en_file
                      })
                  } else {
                      $badFrontMatter.add("$lang\$relative_path")
                  }
              }
              write-host "Finished $lang"
              write-host "$($commitDistances.Count) files have sourceCommit, $($badFrontMatter.Count) files do not have sourceCommit"
          }
          
          $commitDistances.ToArray() | Export-Csv -Path ${{ env.file_distances_name }} -NoTypeInformation
          $badFrontMatter | Out-File -FilePath ${{ env.file_no_sourceCommit_name }} -Encoding ascii
    
      - name: integrate
        run: python integrate.py

      - if: github.event_name == 'workflow_dispatch'
        run: ls

      - uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: output
          path: "output"

      - name: Output artifact ID
        run: |
          echo 'Artifact URL is ${{ steps.artifact-upload.outputs.artifact-url }}'
          echo ${{ steps.artifact-upload.outputs.artifact-url }} > URL.txt
          gc URL.txt
      
      - name: publish
        uses: ./.github/actions/publish
        with:
          filename: URL.txt
          ACCOUNT_TOKEN_GIST: ${{ secrets.ACCOUNT_TOKEN_GIST }}
          TARGET_GIST_ID: ${{ vars.TARGET_GIST_ID }}
