name: publish to gist

on:
  workflow_call:
    inputs:
      filename:
        required: true
        type: string

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ inputs.filename }}

      - name: Update Gist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          head -n 10 ${{ inputs.filename }}
          
          jq -n --arg filename "${{ inputs.filename }}" --rawfile content  "${{ inputs.filename }}" \
            '{files: {($filename): {content: $content}}}' >> json_data
          head -n 10 json_data | cut -c 1-100
          
          response=$(curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "@json_data" \
            "https://api.github.com/gists/${{ vars.TARGET_GIST_ID }}" )
          
          # 检查 curl 的返回状态
          if [ $response["status"] -ne 200 ]; then
            echo "Error: Failed to update Gist."
            echo "$response"
            exit 1
          fi
          
          echo "Gist updated successfully: $response"
