name: publish to gist

on:
  workflow_call:
    inputs:
      filename:
        required: true
        type: string

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ inputs.filename }}
      
      - name: Read file content
        id: read_file
        run: |
          content=$(cat "${{ inputs.filename }}")
          echo "content=$content" >> $GITHUB_ENV

      - name: Update Gist
        run: |
          curl -L \
              -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.ACCOUNT_TOKEN_GIST }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/gists/${{ env.TARGET_GIST_ID }} \
              -d "{\"files\":{\"${{ inputs.filename }}\":{\"content\": \"${{ env.content }}\"}}}"
