name: publish to gist

on:
  workflow_call:
    inputs:
      filename:
        required: true
        type: string
      content:
        required: true
        type: string

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update Gist
        run: |
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACCOUNT_TOKEN_GIST }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/gists/${{ env.TARGET_GIST_ID }} \
            -d '{"files":{${{ toJSON(inputs.filename) }}:{"content":${{ toJSON(inputs.content) }} }}}'
